"""
Column Shop Drawing — Interactive HTML Generator
Produces a standalone HTML file with the interactive SVG column drawing.
Config values are baked into the HTML so the drawing opens pre-populated.
"""

import os
import json
from typing import Dict, List, Optional

from shop_drawings.config import ShopDrawingConfig


def generate_column_html(
    cfg: ShopDrawingConfig,
    col_index: int = 0,
    output_path: Optional[str] = None,
    revision: str = "-",
) -> bytes:
    """
    Generate an interactive HTML column shop drawing with config baked in.

    Args:
        cfg: ShopDrawingConfig with project data
        col_index: Column index (0-based)
        output_path: Optional file path to save HTML
        revision: Revision letter/number

    Returns:
        HTML bytes
    """
    from templates.column_drawing import COLUMN_DRAWING_HTML

    # Build the config dict that applyConfigToDrawing() expects
    config_data = {
        "roof_pitch_deg": cfg.roof_pitch_deg,
        "clear_height_ft": cfg.clear_height_ft,
        "building_width_ft": cfg.building_width_ft,
        "footing_depth_ft": cfg.footing_depth_ft,
        "col_rebar_size": cfg.col_rebar_size,
        "col_reinforced": cfg.col_reinforced,
        "project_name": cfg.project_name,
        "customer_name": cfg.customer_name,
        "job_code": cfg.job_code,
        "drawn_by": cfg.drawn_by,
    }

    # Start with the template HTML
    html = COLUMN_DRAWING_HTML

    # Replace placeholders
    html = html.replace("{{JOB_CODE}}", cfg.job_code or "DRAFT")
    html = html.replace("{{USER_ROLE}}", "admin")
    html = html.replace("{{USER_NAME}}", cfg.drawn_by or "TitanForge")

    # Inject auto-apply script that bakes config directly (no API fetch needed)
    # This replaces the fetch-from-API approach with inline config data
    baked_config_js = f"""
<script>
// ── BAKED CONFIG (generated by TitanForge) ──
document.addEventListener('DOMContentLoaded', function() {{
  const bakedConfig = {json.dumps(config_data)};
  if (typeof applyConfigToDrawing === 'function') {{
    applyConfigToDrawing(bakedConfig);
  }} else {{
    // Fallback: set fields directly
    const fieldMap = {{
      'roof_pitch_deg': 'inPitch',
      'clear_height_ft': 'inClearHt',
      'building_width_ft': 'inWidth',
      'footing_depth_ft': 'inFooting',
      'col_rebar_size': 'inRebar',
      'project_name': 'inProject',
      'customer_name': 'inCustomer',
      'job_code': 'inJobNo',
      'drawn_by': 'inDrawnBy',
    }};
    for (const [k, inputId] of Object.entries(fieldMap)) {{
      const el = document.getElementById(inputId);
      if (el && bakedConfig[k] !== undefined) {{
        el.value = String(bakedConfig[k]);
        el.dispatchEvent(new Event('input', {{ bubbles: true }}));
      }}
    }}
    if (bakedConfig.col_reinforced === false && typeof toggleReinforced === 'function') {{
      toggleReinforced();
    }}
    if (typeof draw === 'function') draw();
  }}
}});
</script>
"""

    # Insert baked config script before closing </body>
    html = html.replace("</body>", baked_config_js + "\n</body>")

    html_bytes = html.encode("utf-8")

    if output_path:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "wb") as f:
            f.write(html_bytes)

    return html_bytes


def generate_all_column_html(
    cfg: ShopDrawingConfig,
    output_dir: str,
    revision: str = "-",
) -> List[str]:
    """
    Generate interactive HTML shop drawings for all unique column types.
    Returns list of output file paths.
    """
    paths = []
    job = cfg.job_code or "DRAFT"

    if cfg.frame_type == "tee":
        path = os.path.join(output_dir, f"{job}_C1.html")
        generate_column_html(cfg, col_index=0, output_path=path, revision=revision)
        paths.append(path)
    else:
        path = os.path.join(output_dir, f"{job}_C1.html")
        generate_column_html(cfg, col_index=0, output_path=path, revision=revision)
        paths.append(path)

    return paths
